name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Upgrade GHCup
      run: ghcup upgrade
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.2.7'
        enable-stack: true
        stack-version: 'latest'
        stack-setup-ghc: true
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
